# This is a little makefile to check if the zlib development package is
# installed; if not, a static version is build and the konto_check library
# is linked against this version.

dynamic:
	@ $(CC) $(CFLAGS) test_zlib.c $(LDFLAGS) -lz -o test_zlib

static: libz.a
	@ $(CC) -Izlib $(CFLAGS) $(LDFLAGS) test_zlib.c libz.a -o test_zlib

libz.a:
	@ gunzip -c < zlib.tar.gz | tar xf - ; cd zlib ; ./configure ; $(MAKE) libz.a ; cp libz.a .. ; make clean

